[package]
name = "vite_rust_plugin"
version = "0.1.0"
edition = "2024"

[dependencies]
napi = { version = "2.16.13"}
napi-derive = "2.16.13"

[build-dependencies]
napi-build = "2.1.3"

[lib]
crate-type = ["cdylib"]